### ISSUE TITLE
Inferencing on Gaudi is failing

### ISSUE THREAD

**Issue by dkiran1** [huggingface/optimum-habana#2211]
Hi,
I used the below code sample to infer the model on Gaudi cluster
import logging
from transformers import AutoTokenizer, AutoModelForCausalLM
from optimum.habana import GaudiTextGenerationPipeline, GaudiConfig

MODEL_NAME = "Qwen/Qwen3-4B-Thinking-2507"  
DEVICE = "hpu"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=False)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map=DEVICE,
    trust_remote_code=True
)

gaudi_config = GaudiConfig(
    use_hpu_graphs=True,        # enable graph compilation for speed
    use_kv_cache=True,          # faster decoding
    attention_op="gaudi_scaled_dot_product_attention"
)
pipe = GaudiTextGenerationPipeline(
    model=model,
    tokenizer=tokenizer,
    gaudi_config=gaudi_config
)
prompt = "Explain the importance of space exploration in simple terms."
output = pipe(
    prompt,
    max_new_tokens=128,
    batch_size=1,
    do_sample=True,
    top_p=0.9,
    temperature=0.7
)
print("\n--- Generated Output ---\n")
print(output[0]["generated_text"])

Iam getting below error ImportError: cannot import name '_VALID_DICT_FIELDS' from 'transformers.training_args' (/usr/local/lib/python3.10/dist-packages/transformers/training_args.py)

Here is my config transformers :- 4.55.2, habana: 1.21.3.57_, optimum-habana 1.18.0 and optimum version 1.27.0 ,Can this be due to version mismatch?  can you please provide the sample inferencing code on Gaudi?

**Comment by regisss** [comment]
`optimum-habana` v1.18 is not compatible with `transformers` v4.55. It requires `transformers` v4.51, please run:
```
pip install transformers==4.51.3
```

Besides, running
```py
from optimum.habana import GaudiTextGenerationPipeline
```
will not work as `GaudiTextGenerationPipeline` is not defined in the source code of the library but in an example: https://github.com/huggingface/optimum-habana/blob/v1.18.1/examples/text-generation/text-generation-pipeline/pipeline.py#L12

**Comment by dkiran1** [comment]
If I use transformers v4.51, Iam getting the below error.
   from transformers.training_args import (
ImportError: cannot import name '_VALID_DICT_FIELDS' from 'transformers.training_args' (/usr/local/lib/python3.10/dist-packages/tra
so I downgraded to 4.49.0. I used the example of pipeline 
import argparse
import logging

from pipeline import GaudiTextGenerationPipeline
from run_generation import setup_parser
import time
# Define a logger
logging.basicConfig(
    format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
    datefmt="%m/%d/%Y %H:%M:%S",
    level=logging.INFO,
)
logger = logging.getLogger(__name__)

# Set up an argument parser
parser = argparse.ArgumentParser()
args = setup_parser(parser)

# Define some pipeline arguments. Note that --model_name_or_path is a required argument for this script
args.num_return_sequences = 1
#args.model_name_or_path = "Qwen/Qwen3-4B-Thinking-2507"
#args.model_name_or_path = "meta-llama/Llama-3.1-8B-Instruct"
#args.model_name_or_path = "./merged_sft_model_phi_sql"
args.model_name_or_path = "microsoft/Phi-3.5-mini-instruct"
args.max_new_tokens = 1000
args.use_hpu_graphs = False
args.batch_size = 2
args.use_kv_cache = True
args.do_sample = True
#args.do_sample = False
print("Args value.. ",args)
# Initialize the pipeline
pipe = GaudiTextGenerationPipeline(args, logger)
 final_prompt = prompt.format(question=question)
 output = pipe(final_prompt)

Its working ok with Qwen 2.5 based models , but giving below error for microsoft-phi3.3 models .
 next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: prob_dist must be 1 or 2 dim

**Comment by regisss** [comment]
This should work with Transformers v4.51, can you paste here the whole error message?

Phi3 is not part of our [list of validated models](https://github.com/huggingface/optimum-habana?tab=readme-ov-file#transformers) so it's not surprising that it doesn't work.

**Comment by regisss** [comment]
What is the code you ran to perform inference with Qwen3?

**Comment by dkiran1** [comment]
Its the same code which i have mentioned above
import argparse
import logging

from pipeline import GaudiTextGenerationPipeline
from run_generation import setup_parser
import time

Define a logger
logging.basicConfig(
format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
datefmt="%m/%d/%Y %H:%M:%S",
level=logging.INFO,
)
logger = logging.getLogger(name)

parser = argparse.ArgumentParser()
args = setup_parser(parser)

args.num_return_sequences = 1
#args.model_name_or_path = "Qwen/Qwen3-4B-Thinking-2507"
#args.model_name_or_path = "meta-llama/Llama-3.1-8B-Instruct"
#args.model_name_or_path = "./merged_sft_model_phi_sql"
args.model_name_or_path = "microsoft/Phi-3.5-mini-instruct"
args.max_new_tokens = 1000
args.use_hpu_graphs = False
args.batch_size = 2
args.use_kv_cache = True
args.do_sample = True
#args.do_sample = False
print("Args value.. ",args)

pipe = GaudiTextGenerationPipeline(args, logger)
final_prompt = prompt.format(question=question)
output = pipe(final_prompt)


What I have observed we are seeing this issue on optimum-habana 1.18.1  for Qwen3 and other few models(fine tuned version of Qwen2.5) . If I downgrade the optimnum-habana to 1.18.0 , then its finedtuned version of Qwen2.5 worked out.

**Comment by regisss** [comment]
Which checkpoint of Qwen2.5 did you use?
