### PR TITLE
Update Mixtral-8x7B Optimization

### PR DESCRIPTION
**Pull request by jychen-habana**
# What does this PR do?

- Update Mixtral-8x7B Optimization:
reuse_cache / enable FP8 KV Cache / FP8 Attn / bucket_internal ...

- Support long sequence prompt
```shell
QUANT_CONFIG=./quantization_config/maxabs_measure.json python run_generation.py \
--model_name_or_path mistralai/Mixtral-8x7B-v0.1  \
--use_hpu_graphs \
--use_kv_cache \
--limit_hpu_graphs \
--reuse_cache \
--bucket_size 128 \
--bucket_internal \
--max_new_tokens 100 \
--bf16 \
--batch_size 1

QUANT_CONFIG=./quantization_config/maxabs_quant_mixtral.json python run_generation.py \
--model_name_or_path mistralai/Mixtral-8x7B-v0.1  \
--use_hpu_graphs \
--use_kv_cache \
--limit_hpu_graphs \
--reuse_cache \
--bucket_internal \
--bucket_size 128 \
--max_new_tokens 100 \
--bf16 \
--fp8 \
--batch_size 2 \
--warmup 1 \
--n_iterations 1 \
--max_input_tokens 32000
```

image

### CODE REVIEW

**Review by mandy-li — CHANGES_REQUESTED** [review]
@jychen-habana , as we sync off-line:
1. kv_cache_fp8 is the previous way to support fp8 inference which will be removed soon. All the models fp8 inference should use HQT.
2. Your current code in this PR causes regression for HQT measurement.

**Comment by mandy-li** [comment]
@schoi-habana , please provide details of how you optimized Falcon-180b fp8 for Jinyan to follow to add to this model. thanks

File: optimum/habana/transformers/models/mixtral/modeling_mixtral.py [hunk 1]
```diff
@@ -327,234 +388,272 @@ def gaudi_mixtral_block_sparse_moe_forward(self, hidden_states: torch.Tensor) ->
...
+            flash_attention_recompute=flash_attention_recompute,
+            cache_idx=cache_idx,
+        )
+        hidden_states = residual + hidden_states
+        htcore.mark_step()
+
+        # Fully Connected
+        residual = hidden_states
+        hidden_states = self.post_attention_layernorm(hidden_states)
+        hidden_states, router_logits = self.block_sparse_moe(hidden_states)
```
Comment (schoi-habana) [inline optimum/habana/transformers/models/mixtral/modeling_mixtral.py:451]: Deepspeed performs autotp on w2 layers in block_sparse_moe.
seems this linear layers have potential to reduce memory consumption by adopting ScopedLinearAllreduce as in this PR
https://github.com/huggingface/optimum-habana/pull/589

**Review by schoi-habana — CHANGES_REQUESTED** [review]

File: optimum/habana/transformers/models/mixtral/modeling_mixtral.py (hunk 1 above)
Comment (jychen-habana) [reply optimum/habana/transformers/models/mixtral/modeling_mixtral.py:451]: Thanks！I will go check this!

File: optimum/habana/transformers/models/mixtral/modeling_mixtral.py [hunk 2]
```diff
@@ -177,105 +185,158 @@ def forward(self, cur, dim, idx):
...
-    else:
-        query_states, key_states, value_states, attention_mask = gaudi_mixtral_repeat_kv(
-            query_states, key_states, value_states, attention_mask, self.num_key_value_groups
-        )
+            query_states, key_states, value_states, attention_mask = gaudi_mixtral_repeat_kv(
+                query_states, key_states, value_states, attention_mask, self.num_key_value_groups
+            )
 
-        attn_weights = torch.matmul(query_states, key_states.transpose(-2, -1)) / math.sqrt(self.head_dim)
+            attn_weights = self.matmul_qk(query_states, key_states.transpose(-2, -1)) * self.norm_factor
```
[the remark this answers is not in the document]
Comment (jychen-habana) [reply optimum/habana/transformers/models/mixtral/modeling_mixtral.py:313]: One question, If FusedSDPA is not chosen, then matlmul_qk matmul-kv are still useful for Attn FP8, is it expected to remove this FP8 on standard Attn and only enable FusedSDPA in the future?

[the remark this answers is not in the document]
Comment (schoi-habana) [reply optimum/habana/transformers/models/mixtral/modeling_mixtral.py:313]: I'm not sure if i understood your question. In the future, FP8 FusedSDPA kernel will be enabled. Then the flow with matmul_qk and matmul_av are no longer needed for FP8. 

FYI, maybe you could review Falcon's code and follow its method to separate BF16 and FP8 cases by using the "QUANT_CONFIG" env var
https://github.com/huggingface/optimum-habana/blob/753da20f98ad6f874075701995428072159ba600/optimum/habana/transformers/models/falcon/modeling_falcon.py#L367

**Comment by schoi-habana** [comment]
I tested this PR with run_generation.py in 1.16.0 docker. It could fit 30k input tokens but the generated output was empty. Did you check the output?

input 1: ('DeepSpeed is a machine learning framework',)
output 1: ('DeepSpeed is a machine learning framework',)

**Comment by schoi-habana** [comment]
@jychen-habana after you implement ScopedLinearAllreduce, please see if this PR https://github.com/HabanaAI/optimum-habana-fork/pull/65 helps this model

**Comment by jychen-habana** [comment]
> I tested this PR with run_generation.py in 1.16.0 docker. It could fit 30k input tokens but the generated output was empty. Did you check the output?
> 
> input 1: ('DeepSpeed is a machine learning framework',) output 1: ('DeepSpeed is a machine learning framework',)

In 1.15 steup env, I didn't get this issue.

**Comment by jychen-habana** [comment]
> @jychen-habana , as we sync off-line:
> 
> 1. kv_cache_fp8 is the previous way to support fp8 inference which will be removed soon. All the models fp8 inference should use HQT.
> 2. Your current code in this PR causes regression for HQT measurement.

fixed.

File: optimum/habana/transformers/models/mixtral/modeling_mixtral.py [hunk 3]
```diff
@@ -567,6 +666,10 @@ class GaudiMixtralForCausalLM(MixtralForCausalLM):
     - from step2 when enable KV cache, slice next_position_ids from position_ids base on the token_idx
     """
 
+    def allocate_kv_cache(self, batch_size, max_seq_len, inp_seq_len, kv_cache_fp8):
+        self.model.allocate_kv_cache(batch_size, max_seq_len, inp_seq_len, kv_cache_fp8)
```
[the remark this answers is not in the document]
Comment (jychen-habana) [reply optimum/habana/transformers/models/mixtral/modeling_mixtral.py]: done.

File: optimum/habana/transformers/models/mixtral/modeling_mixtral.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (jychen-habana) [reply optimum/habana/transformers/models/mixtral/modeling_mixtral.py]: done

**Comment by jychen-habana** [comment]
> @jychen-habana after you implement ScopedLinearAllreduce, please see if in-place addition in this PR [HabanaAI#65](https://github.com/HabanaAI/optimum-habana-fork/pull/65) helps this model

Sure.

File: optimum/habana/transformers/models/mixtral/modeling_mixtral.py [hunk 4]
```diff
@@ -143,139 +139,289 @@ def gaudi_mixtral_repeat_kv(
...
+
+        attn_weight += attn_mask
+        attn_weight = self.softmax(attn_weight, dim=-1, invAttnHead=invAttnHead)
+        attn_weight = torch.dropout(attn_weight, dropout_p, train=True)
+        return self.bmm2(attn_weight, value)
+
+
+class NaiveFlashAttention(nn.Module):
+    @staticmethod
+    def forward(q, k, v, mask, causal, q_bucket_size, k_bucket_size=None, scale=None):
```
[the remark this answers is not in the document]
Comment (jychen-habana) [reply optimum/habana/transformers/models/mixtral/modeling_mixtral.py:197]: This is the naive impl of sliced attention, only slice q, so currently k_bucket_size, scale are not needed, if that still not meet with 32K, then K and V are also need to slice.

File: optimum/habana/transformers/models/mixtral/modeling_mixtral.py [hunk 5]
```diff
@@ -143,139 +139,289 @@ def gaudi_mixtral_repeat_kv(
...
-        if token_idx is not None:
-            if 0 <= self.layer_idx < len(past_key_value.key_cache):
-                past_key_value.key_cache[self.layer_idx].index_copy_(2, token_idx - 1, key_states)
-                past_key_value.value_cache[self.layer_idx].index_copy_(2, token_idx - 1, value_states)
-                key_states = past_key_value.key_cache[self.layer_idx]
-                value_states = past_key_value.value_cache[self.layer_idx]
+            past_key_value = None
+
+        if FusedSDPA:
+            if not self.training and q_len == key_states.size(-2) and q_len >= 8192 and q_len % self.bucket_size == 0:
```
[the remark this answers is not in the document]
Comment (jychen-habana) [reply optimum/habana/transformers/models/mixtral/modeling_mixtral.py:369]: this is the simple version of sliced q, to not padding to the last block. will add last bock padding

File: optimum/habana/transformers/models/mixtral/modeling_mixtral.py [hunk 6]
```diff
@@ -327,234 +474,271 @@ def gaudi_mixtral_block_sparse_moe_forward(self, hidden_states: torch.Tensor) ->
...
-            "Passing `padding_mask` is deprecated and will be removed in v4.37. Please make sure use `attention_mask` instead.`"
-        )
+class GaudiMixtralDecoderLayer(MixtralDecoderLayer):
+    def __init__(self, config: MixtralConfig, layer_idx: int):
+        super().__init__(config, layer_idx)
+        self.hidden_size = config.hidden_size
 
-    htcore.mark_step()
-    residual = hidden_states
+        self.self_attn = MIXTRAL_ATTENTION_CLASSES[config._attn_implementation](config, layer_idx)
```
Comment (schoi-habana) [inline optimum/habana/transformers/models/mixtral/modeling_mixtral.py:482]: do you have to use MIXTRAL_ATTENTION_CLASSES?
since you have only one choice, i think you can directly use GaudiMixtralAttention

File: optimum/habana/transformers/models/mixtral/modeling_mixtral.py (hunk 1 above)
Comment (schoi-habana) [reply optimum/habana/transformers/models/mixtral/modeling_mixtral.py:535]: are you planning to implement ScopedLinearAllreduce?

File: optimum/habana/transformers/models/mixtral/modeling_mixtral.py (hunk 6 above)
Comment (jychen-habana) [reply optimum/habana/transformers/models/mixtral/modeling_mixtral.py:482]: Currently, I plan to keep this choice to let other implementations easily added in if needed. But that's ok to delete it, could do that in the following PR.

File: optimum/habana/transformers/models/mixtral/modeling_mixtral.py [hunk 7]
```diff
@@ -62,33 +69,23 @@
...
-        return torch.cat((prev, cur), dim=dim)
+logger = logging.get_logger(__name__)
 
 
 def apply_customized_rope(q, k, cos, sin, position_ids):
     if q.device.type == "hpu" and FusedRoPE:
         return FusedRoPE.apply(
-            q, cos.unsqueeze(0).unsqueeze(0), sin.unsqueeze(0).unsqueeze(0), position_ids
-        ), FusedRoPE.apply(k, cos.unsqueeze(0).unsqueeze(0), sin.unsqueeze(0).unsqueeze(0), position_ids)
+            q, cos.unsqueeze(0).unsqueeze(0).clone(), sin.unsqueeze(0).unsqueeze(0).clone(), position_ids
```
[the remark this answers is not in the document]
Comment (jychen-habana) [reply optimum/habana/transformers/models/mixtral/modeling_mixtral.py:85]: I checked my profiling trace and the rope is already bf16
image

File: optimum/habana/transformers/models/mixtral/modeling_mixtral.py (hunk 1 above)
Comment (jychen-habana) [reply optimum/habana/transformers/models/mixtral/modeling_mixtral.py:535]: This PR will only include single card optimization, I will submit another PR to add ScopedLinearAllreduce

**Comment by mandy-li** [comment]
@jychen-habana ,  please post the performance measurements with/without this PR here.

**Comment by mandy-li** [comment]
@jychen-habana , please rebase to latest code in OH main branch

**Comment by mandy-li** [comment]
@jychen-habana , this PR doesn't work with Synapse 1.15 release docker when measurement. 

QUANT_CONFIG=./quantization_config/maxabs_measure.json python run_generation.py --model_name_or_path /mnt/weka/data/mixtral/models--mistralai--Mixtral-8x7B-Instruct-v0.1/snapshots/1e637f2d7cb0a9d6fb1922f305cb784995190a83/ --use_hpu_graphs --use_kv_cache --limit_hpu_graphs --bucket_size 128 --max_new_tokens 128 --batch_size 1 --bf16

Error:

File "/home/jwang/test/optimum-habana-jychen/optimum/habana/transformers/models/mixtral/modeling_mixtral.py", line 787, in forward
    outputs = self.model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1564, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/jwang/test/optimum-habana-jychen/optimum/habana/transformers/models/mixtral/modeling_mixtral.py", line 692, in forward
    layer_outputs = decoder_layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1564, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/jwang/test/optimum-habana-jychen/optimum/habana/transformers/models/mixtral/modeling_mixtral.py", line 518, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1564, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/jwang/test/optimum-habana-jychen/optimum/habana/transformers/models/mixtral/modeling_mixtral.py", line 356, in forward
    key_states = self.k_cache.update(past_key_value[0], key_states, 2, token_idx, self.inp_seq_len)
  File "/usr/local/lib/python3.10/dist-packages/habana_quantization_toolkit/_quant_common/helper_modules.py", line 264, in update
    qinput = self.quant_input_0(cur)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1691, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'PatchedKVCache' object has no attribute 'quant_input_0'

**Comment by jychen-habana** [comment]
Will break this PR into small pieces

**Comment by jychen-habana** [comment]
> @jychen-habana , this PR doesn't work with Synapse 1.15 release docker when measurement.
> 
> QUANT_CONFIG=./quantization_config/maxabs_measure.json python run_generation.py --model_name_or_path /mnt/weka/data/mixtral/models--mistralai--Mixtral-8x7B-Instruct-v0.1/snapshots/1e637f2d7cb0a9d6fb1922f305cb784995190a83/ --use_hpu_graphs --use_kv_cache --limit_hpu_graphs --bucket_size 128 --max_new_tokens 128 --batch_size 1 --bf16
> 
> Error:
> 
> File "/home/jwang/test/optimum-habana-jychen/optimum/habana/transformers/models/mixtral/modeling_mixtral.py", line 787, in forward outputs = self.model( File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1564, in _call_impl result = forward_call(*args, **kwargs) File "/home/jwang/test/optimum-habana-jychen/optimum/habana/transformers/models/mixtral/modeling_mixtral.py", line 692, in forward layer_outputs = decoder_layer( File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1564, in _call_impl result = forward_call(*args, **kwargs) File "/home/jwang/test/optimum-habana-jychen/optimum/habana/transformers/models/mixtral/modeling_mixtral.py", line 518, in forward hidden_states, self_attn_weights, present_key_value = self.self_attn( File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1564, in _call_impl result = forward_call(*args, **kwargs) File "/home/jwang/test/optimum-habana-jychen/optimum/habana/transformers/models/mixtral/modeling_mixtral.py", line 356, in forward key_states = self.k_cache.update(past_key_value[0], key_states, 2, token_idx, self.inp_seq_len) File "/usr/local/lib/python3.10/dist-packages/habana_quantization_toolkit/_quant_common/helper_modules.py", line 264, in update qinput = self.quant_input_0(cur) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1691, in **getattr** raise AttributeError(f"'{type(self).**name**}' object has no attribute '{name}'") AttributeError: 'PatchedKVCache' object has no attribute 'quant_input_0'

Please add --reuse_kvcache when measure with bf16, from my understanding, because kvcache need to be an 'nn.Module', then it could be measured. 

For quantization mode, it's fine to just remove --reuse_cache.

Or if there is any solution, please let me know
