### PR TITLE
fix mllama test

### PR DESCRIPTION
**Pull request by sywangyi**
pytest tests/test_examples.py::MultiCardImageToTextModelingLoRAExampleTester::test_run_image2text_lora_finetune_Llama-3.2-11B-Vision-Instruct_multi_card -v -s

Traceback (most recent call last):
File "/workspace/wangyi/optimum-habana/examples/image-to-text/run_image2text_lora_finetune.py", line 553, in
main()
File "/workspace/wangyi/optimum-habana/examples/image-to-text/run_image2text_lora_finetune.py", line 538, in main
anls = eval(
File "/workspace/wangyi/optimum-habana/examples/image-to-text/run_image2text_lora_finetune.py", line 334, in eval
generated_ids = model.generate(
File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "/workspace/wangyi/optimum-habana/optimum/habana/transformers/generation/utils.py", line 1462, in generate
result = self._sample(
File "/workspace/wangyi/optimum-habana/optimum/habana/transformers/generation/utils.py", line 2620, in _sample
eos_positions = (input_ids[:, INITIAL_TOKEN_IDX:] == eos_token_id).int().argmax(dim=1) + INITIAL_TOKEN_IDX
AttributeError: 'bool' object has no attribute 'int'

failure caused by https://github.com/huggingface/optimum-habana/pull/1546

### CODE REVIEW

**Comment by sywangyi** [comment]
@jiminha pls help

**Comment by jiminha** [comment]
@skavulya Could you also review this?

**Comment by jiminha** [comment]
@sywangyi  have you run the original t5 summarization test to see if throughput is same with this fix?

**Comment by jiminha** [comment]
> @sywangyi have you run the original t5 summarization test to see if throughput is same with this fix?

Ok, not sure what's the original t5 command that @ugolowic tested. but I ran just one of the test case and getting simliar result with this changes and without. 

GAUDI2_CI=1  RUN_SLOW=1 python3.10 -m pytest  tests/test_encoder_decoder.py -s -v -k token0-t5-3b-Habana/t5-2.955-21.8877-2-1 

```
`***** predict metrics *****
  predict_gen_len                =      127.0
  predict_loss                   =    15.3285
  predict_model_preparation_time =     5.2246
  predict_rouge1                 =    24.2332
  predict_rouge2                 =     7.1673
  predict_rougeL                 =    16.8835
  predict_rougeLsum              =    21.8323
  predict_runtime                = 0:00:59.40
  predict_samples                =        200
  predict_samples_per_second     =      3.367
  predict_steps_per_second       =      1.683
[INFO|modelcard.py:449] 2024-12-06 19:44:32,816 >> Dropping the following result as it does not have all the necessary fields:
{'task': {'name': 'Summarization', 'type': 'summarization'}, 'dataset': {'name': 'cnn_dailymail 3.0.0', 'type': 'cnn_dailymail', 'args': '3.0.0'}}
PASSED
```
`

**Comment by jiminha** [comment]
> @sywangyi have you run the original t5 summarization test to see if throughput is same with this fix?

GAUDI2_CI=1 RUN_SLOW=1 python3.10 -m pytest tests/test_encoder_decoder.py -s -v -k token0-t5-3b-Habana/t5-2.955-21.8877-2-1

`***** predict metrics *****
  predict_gen_len                =      127.0
  predict_loss                   =    15.3285
  predict_model_preparation_time =     5.2246
  predict_rouge1                 =    24.2332
  predict_rouge2                 =     7.1673
  predict_rougeL                 =    16.8835
  predict_rougeLsum              =    21.8323
  predict_runtime                = 0:00:59.40
  predict_samples                =        200
  predict_samples_per_second     =      3.367
  predict_steps_per_second       =      1.683
[INFO|modelcard.py:449] 2024-12-06 19:44:32,816 >> Dropping the following result as it does not have all the necessary fields:
{'task': {'name': 'Summarization', 'type': 'summarization'}, 'dataset': {'name': 'cnn_dailymail 3.0.0', 'type': 'cnn_dailymail', 'args': '3.0.0'}}
PASSED


vs 
(Yi's fix) 
***** predict metrics *****
  predict_gen_len                =      127.0
  predict_loss                   =    15.3285
  predict_model_preparation_time =     4.7198
  predict_rouge1                 =    24.2332
  predict_rouge2                 =     7.1673
  predict_rougeL                 =    16.8835
  predict_rougeLsum              =    21.8323
  predict_runtime                = 0:00:59.23
  predict_samples                =        200
  predict_samples_per_second     =      3.376
  predict_steps_per_second       =      1.688
[INFO|modelcard.py:449] 2024-12-06 19:52:58,046 >> Dropping the following result as it does not have all the necessary fields:
{'task': {'name': 'Summarization', 'type': 'summarization'}, 'dataset': {'name': 'cnn_dailymail 3.0.0', 'type': 'cnn_dailymail', 'args': '3.0.0'}}
PASSED

**Review by regisss — APPROVED** [review]
