### PR TITLE
Enable Mamba to use PScan Kernel

### PR DESCRIPTION
**Pull request by slokesha**
# What does this PR do?

Mamba model to use the PScan Kernel which will improve its throughput. 
HL-SMI Version:                                   hl-1.22.0-rc-fw-          
Driver Version:                                     1.22.0-48ef525          
Nic Driver Version:                                 1.22.0-48ef525  

image: artifactory-kfs.habana-labs.com/docker-local/1.22.0/ubuntu22.04/habanalabs/pytorch-installer-2.7.1:1.22.0-543

G2:
image

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by karol-brejna-i — APPROVED** [review]
Contains changes in the logic itself, as well as docs and tests.
Looks good.

**Comment by slokesha** [comment]
> @slokesha This doesn't work with SynapseAI v1.21 right?
 
yes it fails with error:
  File "/root/hs/optimum-habana/optimum/habana/transformers/models/mamba/modeling_mamba.py", line 29, in Run_Mamba_Forward_Gaudi
    state_out_h = torch.ops.hpu.mamba_pscan(in_state_h, in_x_h, in_dt_h, in_A_h, in_B_h)
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 1232, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'hpu' object has no attribute 'mamba_pscan'

File: docs/source/index.mdx [hunk 1]
```diff
@@ -113,6 +113,7 @@ In the tables below, ✅ means single-card, multi-card and DeepSpeed have all be
 | ChatGLM     | <div style="text-align:left"><li>DeepSpeed</li></div> |  <div style="text-align:left"><li>Single card</li></div> | <li>[language modeling](https://github.com/huggingface/optimum-habana/tree/main/examples/language-modeling)</li><li>[text generation](https://github.com/huggingface/optimum-habana/tree/main/examples/text-generation)</li> |
 | Qwen2-VL |          |  <div style="text-align:left"><li>Single card</li></div> | <li>[image to text](https://github.com/huggingface/optimum-habana/tree/main/examples/image-to-text)</li> |
 | GLM-4V |          |  <div style="text-align:left"><li>Single card</li></div> | <li>[image to text](https://github.com/huggingface/optimum-habana/tree/main/examples/image-to-text)</li> |
+| Mamba |          | <div style="text-align:left"><li>Single card</li></div> | <li>[text generation](https://github.com/huggingface/optimum-habana/tree/main/examples/text-generation)</li> |
```
Comment (regisss) [inline docs/source/index.mdx:116]: Let's add the same line in the README table: https://github.com/huggingface/optimum-habana/blob/0a5bf68b39987b6bcaa5091d3ae6c9edae128d95/README.md?plain=1#L287

File: tests/test_text_generation_example.py [hunk 2]
```diff
@@ -46,7 +46,7 @@
             ("google/gemma-7b", 1, False, True),
             ("google/gemma-2-9b", 1, False, True),
             ("google/gemma-2-27b", 1, False, True),
-            pytest.param("state-spaces/mamba-130m-hf", 1536, False, False, marks=pytest.mark.skip("Deprecated")),
+            ("state-spaces/mamba-130m-hf", 1536, False, False),
```
Comment (regisss) [inline tests/test_text_generation_example.py:54]: Can you check if these baselines are still valid? https://github.com/huggingface/optimum-habana/blob/0a5bf68b39987b6bcaa5091d3ae6c9edae128d95/tests/baselines/fixture/tests/test_text_generation_example.json#L392-L404
Or maybe update them if it runs faster now?

File: tests/baselines/fixture/tests/test_text_generation_example.json [hunk 3]
```diff
@@ -391,7 +391,7 @@
   },
   "tests/test_text_generation_example.py::test_text_generation_bf16_1x[state-spaces/mamba-130m-hf-1536-False-False]": {
     "gaudi2": {
-      "throughput": 3100.9825044466907
+      "throughput": 20208.867657545277
     },
     "gaudi3": {
```
Comment (regisss) [inline tests/baselines/fixture/tests/test_text_generation_example.json:396]: Gaudi3 baselines are unchanged?
