### PR TITLE
optimize seamless-m4t model for text-to-speech generation

### PR DESCRIPTION
**Pull request by sywangyi**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by sywangyi** [comment]
pipeline running issue addressed by https://github.com/huggingface/transformers/pull/29722

**Comment by sywangyi** [comment]
|  perf | A100 | Gaudi2 |
|-------|------|----------|
| BF16 | 528ms|  250ms|
|FP32 |  410ms| 288 ms|

python3 run_pipeline.py \
    --model_name_or_path facebook/hf-seamless-m4t-medium \
    --text "Hello, my dog is cooler than you!"

**Comment by sywangyi** [comment]
|  perf | A100 | Gaudi2 |
|-------|------|----------|
| BF16 | 87ms|  11ms    |
| FP32 | 102ms|  13ms|

in my env

python3 run_pipeline.py \
    --model_name_or_path facebook/mms-tts-eng \
    --text "Hello, my dog is cooler than you!" \
    --use_hpu_graphs \
    --n_iterations 10

**Comment by skaulintel** [comment]
@sywangyi Can you please add test-cases. What is the comparison with GPU?

**Comment by sywangyi** [comment]
C1 tests will be added after https://github.com/huggingface/optimum-habana/pull/834 is merged since it will be added in the same file following similar style.

File: tests/test_pipeline.py [hunk 1]
```diff
@@ -55,3 +91,19 @@ def test_image_to_text_vit(self):
...
+    def test_text_to_speech_speecht5(self):
+        model = "microsoft/speecht5_tts"
+        expected_result = 16000
+        self._test_text_to_speech(model, expected_result)
+
+    def test_text_to_speech_m4t(self):
+        model = "facebook/hf-seamless-m4t-medium"
+        expected_result = 16000
+        if packaging.version.parse(transformers.__version__) >= packaging.version.parse("4.40.0"):
+            self._test_text_to_speech(model, expected_result)
```
Comment (skaulintel) [inline tests/test_pipeline.py:104]: `Traceback (most recent call last):
  File "/root/optimum-habana/tests/test_pipeline.py", line 104, in test_text_to_speech_m4t
    self._test_text_to_speech(model, expected_result)
  File "/root/optimum-habana/tests/test_pipeline.py", line 81, in _test_text_to_speech
    output = generator(text, forward_params=forward_params, generate_kwargs=generate_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/text_to_audio.py", line 182, in __call__
    return super().__call__(text_inputs, **forward_params)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py", line 1242, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py", line 1249, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py", line 1149, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/text_to_audio.py", line 143, in _forward
    output = self.model.generate(**model_inputs, **forward_params)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/models/seamless_m4t/modeling_seamless_m4t.py", line 762, in gaudi_SeamlessM4TForTextToSpeech_generate
    text_generation_output = super(SeamlessM4TForTextToSpeech, self).generate(input_ids, **kwargs_text)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/generation/utils.py", line 805, in generate
    generation_mode = self._get_generation_mode(generation_config, assistant_model)
  File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/core/weight_sharing.py", line 73, in wrapped__getattr__
    result = self.original__get_attr__(name)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1691, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SeamlessM4TForTextToSpeech' object has no attribute '_get_generation_mode'
`

I see the above issue when running the m4t test after downloading transformers 4.40.0. The other tests seem to pass

Comment (sywangyi) [reply tests/test_pipeline.py:104]: It is caused by https://github.com/huggingface/transformers/pull/29441/files. and should be fixed when upgrading transformers in optimum-habana

Comment (regisss) [reply tests/test_pipeline.py:104]: Let's wait for the upgrade to Transformers v4.40 in Optimum Habana before merging this one then

File: tests/test_pipeline.py [hunk 2]
```diff
@@ -46,6 +50,38 @@ def _test_image_to_text(self, model, expected_result):
...
+                forward_params = {"tgt_lang": "eng"}
+
+            generate_kwargs = None
+            if generator.model.can_generate():
+                generate_kwargs = {"lazy_mode": True, "ignore_eos": False, "hpu_graphs": True}
+
+            generator.model = wrap_in_hpu_graph(generator.model)
+            with torch.autocast(
+                "hpu", torch.bfloat16, enabled=(model_dtype == torch.bfloat16)
+            ), torch.no_grad(), torch.inference_mode():
```
Comment (regisss) [inline tests/test_pipeline.py:79]: `torch.no_grad()` and `torch.inference_mode()` are a bit redundant no?
I think we can just keep `torch.inference_mode()`.

File: tests/test_pipeline.py [hunk 3]
```diff
@@ -55,3 +91,19 @@ def test_image_to_text_vit(self):
...
+    def test_text_to_speech_m4t(self):
+        model = "facebook/hf-seamless-m4t-medium"
+        expected_result = 16000
+        if packaging.version.parse(transformers.__version__) >= packaging.version.parse("4.40.0"):
+            self._test_text_to_speech(model, expected_result)
+
+    def test_text_to_speech_mms(self):
+        model = "facebook/mms-tts-eng"
+        expected_result = 16000
+        self._test_text_to_speech(model, expected_result)
```
Comment (regisss) [inline tests/test_pipeline.py:109]: We can have only one method called `test_text_to_speech` with the `@pytest.mark.parametrize(...)` decorator to avoid defining one test per model. Here is an example: https://github.com/huggingface/optimum-habana/blob/574702cd6b4e755cb3673806671352c0e6d3957b/tests/test_text_generation_example.py#L245

File: optimum/habana/transformers/generation/utils.py [hunk 4]
```diff
@@ -241,14 +246,46 @@ def _prepare_decoder_input_ids_for_generation(
             isinstance(decoder_start_token_id, torch.Tensor)
             and (decoder_input_ids[:, 0] != decoder_start_token_id[:, 0]).all().item()
         ):
-            decoder_input_ids = torch.cat([decoder_input_ids_start, decoder_input_ids], dim=-1)
+            if token_idx is None:
+                decoder_input_ids = torch.cat([decoder_input_ids_start, decoder_input_ids], dim=-1)
+            else:
+                max_length = max_new_tokens + 2 if max_new_tokens is not None else self.generation_config.max_length
```
[the remark this answers is not in the document]
Comment (sywangyi) [reply optimum/habana/transformers/generation/utils.py:252]: in this if case, 2 is decoder_input_ids[:, 0] + decoder_start_token_id, facebook/hf-seamless-m4t-medium hit such case

File: examples/text-to-speech/run_pipeline.py [hunk 5]
```diff
@@ -72,7 +79,7 @@ def main():
     elif args.batch_size < text_bs:
         text = text[: args.batch_size]
 
-    if args.bf16:
+    if args.bf16 and "mms-tts-eng" not in args.model_name_or_path:
```
[the remark this answers is not in the document]
Comment (sywangyi) [reply examples/text-to-speech/run_pipeline.py]: work well, remove it in if

**Comment by ssarkar2** [comment]
Merged to master (with transformer 4.40), ran ` python3 run_pipeline.py --model_name_or_path facebook/hf-seamless-m4t-medium --text "Hello, my dog is cooler than you!" --use_hpu_graphs --n_iterations 10`

finished:
```
05/31/2024 21:29:17 - INFO - __main__ - speech = [{'audio': array([[-0.00172372, -0.00146204, -0.00160711, ...,  0.01203394,
         0.01085523,  0.00866978]], dtype=float32), 'sampling_rate': 16000}] time = 2362.2106075286865ms
```

**Comment by sywangyi** [comment]
generated wav file doesn't sound right. this issue is fixed by https://github.com/huggingface/optimum-habana/pull/1034

**Review by ssarkar2 — COMMENTED** [review]
lgtm

**Review by regisss — APPROVED** [review]
