### ISSUE TITLE
GPTJAttention.forward() got an unexpected keyword argument 'token_idx'

### ISSUE THREAD

**Issue by IT-Forrest** [huggingface/optimum-habana#847]
### System Info

```shell
Optimum habana main branch, Synapse version 1.15, docker image 1.15.0:474 (RC)
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Follow the steps in examples/language-modeling https://github.com/huggingface/optimum-habana/tree/main/examples/language-modeling#multi-card-training-with-deepspeed-gpt-j 
and run the following cmd:
```
python ../gaudi_spawn.py \
    --world_size 8 --use_deepspeed run_clm.py \
    --model_name_or_path EleutherAI/gpt-j-6b \
    --dataset_name wikitext \
    --dataset_config_name wikitext-2-raw-v1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --do_train \
    --do_eval \
    --output_dir /tmp/test-clm-xl-1 \
    --gaudi_config_name Habana/gpt2 \
    --use_habana \
    --use_lazy_mode \
    --gradient_checkpointing \
    --use_hpu_graphs_for_inference \
    --throughput_warmup_steps 3 \
    --deepspeed path_for_deepspeed_config
```
Here, the path_for_deepspeed_config is acquired from DeepSpeed Zero-2 config, e.g. https://github.com/huggingface/optimum-habana/blob/main/tests/configs/deepspeed_zero_2.json

Then the flow keeps running and crashes with the `TypeError: GPTJAttention.forward() got an unexpected keyword argument 'token_idx'`
![image](https://github.com/huggingface/optimum-habana/assets/9160073/a5e0ecde-2952-49d5-82b3-17a8844f85c4)

### Expected behavior

The expected behavior is to finish the training and evaluation successfully without any error

**Comment by regisss** [comment]
@IT-Forrest Are you still encountering this error? It works on my side on Synapse 1.14 and I don't think version 1.15 changes anything here.
Have you modified the `run_clm.py` example?

**Comment by IT-Forrest** [comment]
Hi @regisss, thanks for your reaching out. The issue of missing "token_idx" is walked around by downgrading the transformer version from the latest 4.39.3 to 4.38.2, e.g. **pip install transformers==4.38.2** and downgrade pytest version from 8.1.1 to **7.4.4**

The reason that my Transformers version is **4.39.3** is that, after **pip install** latest dependencies, I'll hit the following pytest error when launching the run_clm.py
- pip install git+https://github.com/huggingface/optimum-habana.git  (latest version 1.15)
- pip install git+https://github.com/HabanaAI/DeepSpeed.git  (latest version 1.11)
- pip install -r examples/language-modeling/requirements.txt

![image](https://github.com/huggingface/optimum-habana/assets/9160073/1301dfdd-61d4-4002-8e5b-3cd1b449507c)


With further analysis, the pytest error could be resolved by downgrading pytest version from 8.1.1 to 7.4.4.
Here, pytest 8.1.1 is preinstalled in the latest docker image e.g. `vault.habana.ai/gaudi-docker/1.15.0/ubuntu22.04/habanalabs/pytorch-installer-2.2.0:latest`


Further check the `optimum-habana/setup.py`,  it shows the `pytest version < 8.0.0`, however, **this requirement didn't take effect during the pip install** and thus lead to the pytest issue. 
![image](https://github.com/huggingface/optimum-habana/assets/9160073/cc15b801-2ff7-49b6-a670-66ae30d19d9c)

Anyway, the solution to this ticket is to install the transformers with a consistent version. and I'll close this ticket. Thanks for the help

**Comment by regisss** [comment]
>  pytest 8.1.1 is preinstalled in the latest docker image e.g. vault.habana.ai/gaudi-docker/1.15.0/ubuntu22.04/habanalabs/pytorch-installer-2.2.0:latest

Indeed, that is why we added recently `pytest version < 8.0.0`.
However, `pytest` is not installed with the regular lib because we usually only need it for tests. To have `pytest` installed following the `< 8.0.0` requirement, you'll have to run
```
pip install "optimum-habana[tests] @ git+https://github.com/huggingface/optimum-habana.git"
```
This command enables to install the lib directly from source  and to specify the `[tests]` extra.

**Comment by IT-Forrest** [comment]
Hi @regisss , thanks for your info. Could you please move `pytest version < 8.0.0` into **INSTALL_REQUIRES**?
I can confirm that, `pytest version < 8.0.0` in **INSTALL_REQUIRES** could force pytest downgrade from 8.1.1 to 7.4.4, while in **TESTS_REQUIRE** can't help

Please let me know if you want me to git push a fix to optimum-habana-fork and then optimum-habana? E.g. the diff file is as follows:
```
$ git diff
diff --git a/setup.py b/setup.py
index c822c41..70f6de6 100644
--- a/setup.py
+++ b/setup.py
@@ -34,10 +34,10 @@ INSTALL_REQUIRES = [
     "torch",
     "accelerate < 0.28.0",
     "diffusers >= 0.26.0, < 0.27.0",
+    "pytest < 8.0.0",
 ]

 TESTS_REQUIRE = [
-    "pytest < 8.0.0",
     "psutil",
     "parameterized",
     "GitPython",


```

**Comment by regisss** [comment]
Arf yes, I always test installing the lib with the "tests" extra so I've never encountered this error...
I'm going to apply the fix you suggested as a workaround but ultimately `pytest` should not be installed in the Habana Docker image.

**Comment by regisss** [comment]
@IT-Forrest The fix has just been merged into main. It will also be part of our next patch release which will be out soon.
